services:
  #container for mongodb
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db
      
  #container for apis
  apis:
    container_name: api_container
    build: .
    ports:
      - 4000:8000
    environment:
      PORT: 8000
      DB_NAME: blog-site
      MONGO_URI: mongodb://mongo_db:27017
    depends_on:
      - mongo_db

volumes:
  mongo_db:
